# Generated by Django 2.0.2 on 2018-04-09 06:30

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('albumart', models.ImageField(upload_to=music.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=30)),
                ('audio_file', models.FileField(upload_to=music.models.upload_location)),
                ('song_image', models.ImageField(default=True, upload_to=music.models.upload_location)),
            ],
        ),
    ]
