# Generated by Django 2.0.2 on 2018-04-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='music.Playlist'),
        ),
    ]
